In [54]:
import pandas as pd

In [66]:
cleaned_test_set_with_context = pd.read_csv("data/ipcc_cleaned_test_set_with_context.csv")
original_extracted_sentences = pd.read_csv("data/text_processing/sentences_with_ratings_all.csv")

In [67]:
cleaned_test_set_with_context.head()

,statement_idx,report,page_num,sent_num,statement,confidence,score,split,needs_rewriting,rewriting_done,reason,rewrite,context
0,3,AR6_WGI,24,2,"Since 1750, increases in CO2 (47%) and CH4 (15...",very high,3,test,N,NaN,NaN,NaN,Estimates account for both direct emissions in...
1,42,AR6_WGI,37,16,"Over the next 2000 years, global mean sea leve...",low,0,test,N,NaN,NaN,NaN,Continued ice loss over the 21st century is vi...
2,77,AR6_WGI,47,7,"By the end of the century, scenarios with very...",high,2,test,Y,Y,"acronym: CID, GHG","By the end of the century, scenarios with very...","{6.6, 6.7, Box TS.7}. D.2.3 Scenarios with ver..."
3,81,AR6_WGI,62,2,"Over the past millennium, and especially since...",medium,1,test,N,NaN,context: what reconstructions?,NaN,"{1.3.2, 1.5.1, Cross-Chapter Boxes 2.1 and 2.4..."
4,86,AR6_WGI,63,8,The paleo context supports the assessment that...,high,2,test,N,NaN,NaN,NaN,"For example, under a past global warming level..."

In [68]:
original_extracted_sentences.head()

,Unnamed: 0,filenames,page_num,sent_num,text,confidence_rating
0,0,data/raw/IPCC_AR6_WGI_FullReport.pdf,20,22,"Since 2011 (measurements reported in AR5), con...",high
1,1,data/raw/IPCC_AR6_WGI_FullReport.pdf,21,8,Mid-latitude storm tracks have likely shifted ...,medium
2,2,data/raw/IPCC_AR6_WGI_FullReport.pdf,21,18,The average rate of sea level rise was 1.3 [0....,high
3,3,data/raw/IPCC_AR6_WGI_FullReport.pdf,24,2,"Since 1750, increases in CO 2 (47%) and CH 4 (...",very high
4,4,data/raw/IPCC_AR6_WGI_FullReport.pdf,24,4,Temperatures during the most recent decade (20...,medium

In [69]:
final_test_set = cleaned_test_set_with_context[["statement_idx", "report", "page_num", "sent_num", "confidence", "score", "split", "context", "statement", "rewrite"]]
original_extracted_sentences.reset_index(inplace=True)
original_extracted_sentences.rename(columns={"index": "statement_idx"}, inplace=True)
final_test_set = final_test_set.merge(original_extracted_sentences[["statement_idx", "text"]], on="statement_idx")

final_test_set.rename(columns={"text": "original_statement"}, inplace=True)
final_test_set['final_statement'] = final_test_set.apply(lambda row: row['rewrite'] if pd.notna(row['rewrite']) else row['statement'], axis=1)
final_test_set = final_test_set[["statement_idx", "report", "page_num", "sent_num", "original_statement", "final_statement", "confidence", "score", "split", "context"]]

In [70]:
final_test_set.head()

,statement_idx,report,page_num,sent_num,original_statement,final_statement,confidence,score,split,context
0,3,AR6_WGI,24,2,"Since 1750, increases in CO 2 (47%) and CH 4 (...","Since 1750, increases in CO2 (47%) and CH4 (15...",very high,3,test,Estimates account for both direct emissions in...
1,42,AR6_WGI,37,16,"Over the next 2000 years, global mean sea leve...","Over the next 2000 years, global mean sea leve...",low,0,test,Continued ice loss over the 21st century is vi...
2,77,AR6_WGI,47,7,"By the end of the century, scenarios with very...","By the end of the century, scenarios with very...",high,2,test,"{6.6, 6.7, Box TS.7}. D.2.3 Scenarios with ver..."
3,81,AR6_WGI,62,2,"Over the past millennium, and especially since...","Over the past millennium, and especially since...",medium,1,test,"{1.3.2, 1.5.1, Cross-Chapter Boxes 2.1 and 2.4..."
4,86,AR6_WGI,63,8,This paleo context supports the assessment tha...,The paleo context supports the assessment that...,high,2,test,"For example, under a past global warming level..."

In [71]:
final_test_set.to_csv("data/ipcc_test_set_original_cleaned_context.csv")